
- name: Check if Google Earth GPG key file exists | Internet
  ansible.builtin.stat:
    path: "{{ earth_gpg_key }}"
  register: google_key_file

- name: Download earth_gpg GPG key and convert it | Internet
  ansible.builtin.command: >
    bash -c "wget -q -O - {{ earth_gpg }} | gpg --dearmor | tee {{ earth_gpg_key }}"
  when: not google_key_file.stat.exists

- name: Add Google Earth repository | Internet
  ansible.builtin.lineinfile:
    dest: "{{ earth_repo_name }}"
    line: "{{ earth_repo }}"
    state: present
    create: yes

- name: Install Google Earth | Internet
  ansible.builtin.package:
    name: "{{ earth_pkg }}"
    state: present
    update_cache: yes
