namespace: brcak_zmaj
name: almir_ansible
version: 1.0.1
readme: README.md
authors:
  - almir
description: Ansible roles and collections for server management tasks
license:
  - GPL-3.0-or-later
repository: https://github.com/brcak-zmaj/almir.ansible
dependencies: {}
