---

- name: Configure kernel parameters (common)
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: no  # Disable per-task reload
  loop: "{{ common_sysctl_settings }}"
  notify: reload sysctl  # Defer to handler
  tags: [sysctl]

- name: Include OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  when: ansible_os_family in ['RedHat', 'Debian']