---
- name: Include libvirt tasks
  ansible.builtin.include_tasks: libvirt.yml
  when: libvirt is defined and libvirt == true

- name: Include VirtualBox tasks
  ansible.builtin.include_tasks: virtualbox.yml
  when: virtualbox is defined and virtualbox == true
