---

#########################  DEBIAN #########################

- name: Apt signing key for Brave | Internet 
  when: ansible_os_family == "Debian"
  become: true
  ansible.builtin.apt_key:
    url: "{{ brave_keyring }}"
    validate_certs: true
  tags: gpg_key  

- name: Download Brave Browser keyring
  get_url:
    url: "{{ brave_keyring }}"
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'
  become: true
  tags: gpg_key

- name: Add Brave Browser repository
  ansible.builtin.apt_repository:
    repo: "{{ brave_repo }}"
    state: present
    filename: "brave-browser-release"
    update_cache: yes
  become: yes
  tags: gpg_key

- name: Instal Brave
  become: true
  ansible.builtin.package:
    name: "{{ brave_pkg_name }}"
    update_cache: true