---

#########################  REDHAT #########################

- name: Add Yum signing key Brave | Internet
  become: true
  when: ansible_os_family == "RedHat"  
  ansible.builtin.rpm_key:
    key: "{{ brave_gpgkey }}"
    state: present

- name: Add Brave repository into repo.d list | Internet
  become: true
  when: ansible_os_family == "RedHat"  
  ansible.builtin.yum_repository:
    name: brave-browser
    description: brave repository
    baseurl: "{{ brave_baseurl }}"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ brave_gpgkey }}"

- name: Instal Brave
  become: true
  ansible.builtin.package:
    name: "{{ brave_pkg_name }}"
    update_cache: true