---
- name: Install necessary packages for managing locales (Debian-based)
  become: true
  ansible.builtin.package:
    name:
      - localepurge
      - locales
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure locale is generated (Debian-based)
  become: true
  ansible.builtin.command: "locale-gen {{ locale_lang }}"
  when: ansible_os_family == "Debian"
  changed_when: false

- name: Set locale in locale.gen (Debian-based)
  become: true
  ansible.builtin.lineinfile:
    path: "{{ locale_conf_path_debian }}"
    regexp: '^#?{{ locale_lang }}'
    line: "{{ locale_lang }}"
  when: ansible_os_family == "Debian"
  changed_when: false

- name: Remove non-English locales (Debian-based)
  become: true
  ansible.builtin.command: "localepurge --keep en"
  when: ansible_os_family == "Debian"
  changed_when: false

- name: Ensure English is set as the default system locale (Debian-based)
  become: true
  ansible.builtin.shell: |
    update-locale LANG={{ locale_lang }} LANGUAGE="en_US:en"
  when: ansible_os_family == "Debian"
  changed_when: false

- name: Remove Installed Packages (Debian-based)
  become: true
  ansible.builtin.package:
    name:
      - localepurge
      - locales
    state: absent
  when: ansible_os_family == "Debian"
