---


#########################  General #########################

- name: Remove preinstalled clutter from home directory | Prep 
  ansible.builtin.file:
    path: "{{ home_dir}}/{{ item }}"
    state: absent
  loop: "{{ home_dir_clutter }}"

#########################  Packages #########################

- name: Install Common Packages | Prep
  ansible.builtin.package:
    pkg: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"
  when: utilities is defined and utilities == true

- name: Include {{ ansible_os_family }} packages installation tasks | Prep
  include_tasks: "{{ ansible_os_family | lower }}_packages.yml"
  when: utilities is defined and utilities == true

- name: Include Flatpak task | Prep
  include_tasks: flatpak.yml
  when: flatpak is defined and flatpak == true

- name: Include konsole task | Prep
  include_tasks: konsole.yml
  when: konsole is defined and konsole == true
