---


# vzdump vars
vzdump_tmpdir: "/mnt/backups"   # Overriding default tmpdir path
vzdump_dumpdir: "/mnt/backups/dumps"  # Enable dumpdir and set its path
vzdump_storage: "local-backup"  # Enable storage configuration
vzdump_mode: "snapshot"         # Enable backup mode
vzdump_bwlimit: 4096            # Set bandwidth limit (in KB)
vzdump_ionice: 2                # Set ionice class value
vzdump_lockwait: 5              # Enable lockwait (in minutes)
vzdump_stopwait: 10             # Enable stopwait (in minutes)
vzdump_stdexcludes: true        # Enable stdexcludes (exclude system directories)
vzdump_mailto: "admin@example.com"  # Enable mail notifications
vzdump_prune_backups: "keep-daily=7,keep-weekly=4,keep-monthly=12"  # Enable prune backups
vzdump_script: []  # Specify pre/post backup script
vzdump_exclude_path: "/home/user/temp"  # Specify directories to exclude

# PVE
pve_repo_type: no-subscription

# CPU Performance Governor Vars
cpu_governor_pkg: linux-cpupower
pve_set_cpu: no
pve_cpu_governor: performance


proxmox_ve__net_template: "interfaces.j2"

# Kernel Same-page Merging (KSM)
ksm_ps_metric: "pss"
ksm_logfile_path: "/var/log/ksmtuned"
ksm_debug: 1
ksmtuned_pkg: ksmtuned
ksmtuned_conf: "/etc/ksmtuned.conf"
# Default values for ksmtuned configuration for 128GB Memory
ksm_monitor_interval: 60       # Default, keep it at 60 seconds for tuning intervals
ksm_sleep_msec: 20             # Faster memory sharing scan (smaller servers sleep more)
ksm_npages_boost: 300          # Boost factor for KSM page sharing
ksm_npages_decay: -50          # Decay factor for KSM pages
ksm_npages_min: 64             # Minimum number of pages for KSM sharing
ksm_npages_max: 1250           # Maximum number of pages for KSM sharing
ksm_threshold_coef: 20         # Moderate KSM aggressiveness for 128GB memory
ksm_threshold_const: 2048      # Threshold constant for memory sharing

# Default values for ksmtuned configuration for 256GB Memory
#ksm_monitor_interval: 60        # Default, keep it at 60 seconds for tuning intervals
#ksm_sleep_msec: 10             # Faster memory sharing scan (larger systems can share more frequently)
#ksm_npages_boost: 300          # Boost factor for KSM page sharing
#ksm_npages_decay: -50          # Decay factor for KSM pages
#ksm_npages_min: 64             # Minimum number of pages for KSM sharing
#ksm_npages_max: 1250           # Maximum number of pages for KSM sharing
#ksm_threshold_coef: 10         # More aggressive KSM sharing for 256GB memory
#ksm_threshold_const: 1024      # Lower threshold constant for better performance


common_packages:
  - module-assistant
  - aria2
  - apt-transport-https
  - debian-archive-keyring
  - ca-certificates
  - curl
  - zfsutils-linux
  - build-essential
  - dialog
  - gnupg-agent
  - grc
  - htop
  - iftop
  - iotop
  - iperf
  - ipset
  - iptraf
  - mlocate
  - msr-tools
  - nano
  - net-tools
  - software-properties-common
  - unzip
  - wget
  - cifs-utils

additional_packages:
  - wget  # Placeholder 