
## Dash to dock ---------------------------------------------------------
gnome_shell_extensions_packages:
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extensions

gnome_packages:
  - gnome-extensions-app            # Manage and configure GNOME Shell extensions
  - gnome-tweaks                    # Advanced GNOME desktop configuration tool

# Common system packages to be installed
common_packages:
  # Version Control and Development Tools
  - git                             # Version control system
  - curl                            # Tool for transferring data with URLs
  - unzip                           # Extract ZIP archives
  - wget                            # Command-line file downloader
  - wine                            # Compatibility layer for running Windows applications on Linux
  - keepassxc                       # Password manager

  # System Monitoring and Optimization
  - htop                            # Interactive process viewer
  - iftop                           # Network bandwidth usage monitor
  - iotop                           # Display I/O usage by processes
  - tlp                             # Advanced Linux power management tool

  # Network and Security Tools
  - iperf                           # Network performance testing tool
  - nmap                            # Network scanning tool
  - net-tools                       # Deprecated but still-used network utilities (ifconfig, netstat, etc.)
  - wireshark                       # Network protocol analyzer for troubleshooting and analysis
  - cifs-utils                      # Tools for mounting and managing CIFS/SMB shares

  # Media and Audio Tools
  - flac                            # Free Lossless Audio Codec (audio compression tool)
  - kdenlive                        # Non-linear video editor for Linux

  # Miscellaneous Utilities
  - cowsay                          # ASCII art generator with cows
  - aria2                           # High-speed download utility for HTTP, FTP, and BitTorrent
  - gparted                         # Graphical partition editor
  - bleachbit                       # Disk space cleaner and privacy manager
  - make                            # Utility for building and compiling software
  - bash-completion                 # Programmable tab completion for bash
  - blueman                         # Bluetooth manager for GTK desktops
  - chromium                        # Open-source web browser
  - obs-studio                      # Open source software for video recording and live streaming
  - ripgrep                         # Fast text searcher with regex support

# Debian-Specific Development and Build Tools
debian_packages:
  - build-essential                 # Essential tools for building software
  - gnupg-agent                     # GNU Privacy Guard agent for key management
  - software-properties-common      # Manage software repositories
  - apt-transport-https             # Transport for accessing HTTPS repositories
  - neofetch                        # Display system information
  - vlc                             # Media player supporting various audio and video formats
  - ffmpeg                          # Multimedia processing tool (audio/video)
  - flameshot                       # Screenshot tool with annotation features

  # Debian-Specific Utilities and System Tools
  - dialog                          # Utility for creating dialog boxes from shell scripts
  - grc                             # Generic colorizer for command outputs
  - ncdu                            # Disk usage analyzer
  - iptraf                          # Real-time network monitoring tool
  - kdenlive                        # Non-linear video editor for Linux
  - bashtop                         # Resource monitor for Linux
  
# RedHat-Specific Development and Build Tools
redhat_packages:
  - kernel-devel                    # Development files for building kernel modules
  - kernel-headers                  # Header files for kernel development
  - gcc                             # GNU C compiler
  - dkms                            # Dynamic kernel module support framework
  - pkgconfig                       # Manage compiler and linker flags for libraries
  - fastfetch                       # Modern system fetch utility
  - btop                            # Advanced resource monitor (modern alternative to htop/bashtop)
  - sos                             # Support utility for system diagnostics
  - ncdu                            # Disk usage analyzer
  - btrfs-assistant                 # GUI tool for managing Btrfs volumes
  - snapper                         # Tool for managing Btrfs snapshots

# Nvidia GPU Packages
  - akmod-nvidia
  - xorg-x11-drv-nvidia-cuda