## python ---------------------------------------------------------
python_packages:
  - python3
  - python3-pip

pip_packages:
  - requests              # Simple HTTP library for Python
  - bandit                # Security linter for Python code
  - flake8                # Tool for enforcing coding style in Python
  - pyflakes              # Static analysis tool for Python code
  - pycodestyle           # Style guide checker for Python
  - yapf                  # Code formatter for Python
  - pre-commit            # Framework for managing and maintaining multi-language pre-commit hooks
  - mkdocs                # Documentation tool that generates static site from Markdown files
  - glances               # Cross-platform system monitoring tool
  - socli                 # Command line interface for StackOverflow
  - lorem                 # Generates random Lorem Ipsum text
  - algoliasearch         # Python client for Algolia search service
  - pwgen                 # Password generator
  - glob2                 # Enhanced version of the glob module (wildcard matching)
  - python-gitlab         # GitLab API client for Python
  - docker                # Python SDK for Docker
  - memoization           # Memoization tools for Python functions
  - PyGithub              # Python client for the GitHub API
  - Cloudflare            # Cloudflare API client for Python
  - ansible-lint          # Linter for Ansible playbooks
  - dateparser            # Parsing dates from strings in multiple formats
  - jinja2                # Template engine for Python
  - python-frontmatter    # Parses front matter from files (e.g., Markdown, YAML)
  - validator-collection  # Collection of validators for various data types
  - invoke                # Python task execution library
  - cachetools            # Extensible memoizing collections and decorators
  - certifi               # Python package for providing Mozilla's root certificates
  - chardet               # Universal character encoding detector
  - greenlet              # Lightweight in-process concurrent programming
  - idna                  # International Domain Names (IDN) library
  - msgpack               # Efficient binary serialization format
  - neovim                # Python client for Neovim editor
  - prometheus-client     # Prometheus monitoring client for Python
  - requests              # (Repeated) Simple HTTP library for Python
  - urllib3               # HTTP library with connection pooling
  - proxmoxer             # Python client for Proxmox API