
fqcn[action-core]: Use FQCN for builtin module actions (meta).
/mnt/software/Ansible/roles/general-sysctl-tuning/tasks/main.yml:86 Use `ansible.builtin.meta` or `ansible.legacy.meta` instead.

name[missing]: All tasks should be named.
/mnt/software/Ansible/roles/general-sysctl-tuning/tasks/main.yml:86 Task/Handler: meta flush_handlers

yaml[empty-lines]: Too many blank lines (1 > 0)
/mnt/software/Ansible/roles/general-sysctl-tuning/tasks/main.yml:87

Read documentation for instructions on how to ignore specific rule violations.

                             Rule Violation Summary                              
 count tag                             profile    rule associated tags           
     1 load-failure[filenotfounderror] min        core, unskippable              
     2 deprecated-module               basic      deprecations                   
    57 literal-compare                 basic      idiom                          
     1 jinja[spacing]                  basic      formatting (warning)           
     1 no-free-form                    basic      syntax, risk                   
    50 partial-become[task]            basic      unpredictability               
     1 role-name[path]                 basic      deprecations, metadata         
     1 schema[meta]                    basic      core                           
     2 schema[tasks]                   basic      core                           
     1 schema[vars]                    basic      core                           
    68 name[missing]                   basic      idiom                          
     7 var-naming[pattern]             basic      idiom                          
     6 yaml[colons]                    basic      formatting, yaml               
     3 yaml[comments]                  basic      formatting, yaml               
    23 yaml[empty-lines]               basic      formatting, yaml               
    20 yaml[indentation]               basic      formatting, yaml               
     2 yaml[key-duplicates]            basic      formatting, yaml               
     1 yaml[line-length]               basic      formatting, yaml               
    44 yaml[new-line-at-end-of-file]   basic      formatting, yaml               
     1 yaml[octal-values]              basic      formatting, yaml               
   198 yaml[trailing-spaces]           basic      formatting, yaml               
   133 yaml[truthy]                    basic      formatting, yaml               
    63 name[casing]                    moderate   idiom                          
     9 package-latest                  safety     idempotency                    
     7 risky-file-permissions          safety     unpredictability               
    21 ignore-errors                   shared     unpredictability               
     3 no-changed-when                 shared     command-shell, idempotency     
     1 no-handler                      shared     idiom                          
   234 fqcn[action-core]               production formatting                     
    48 fqcn[action]                    production formatting                     
     2 args[module]                               syntax, experimental (warning) 

Failed: 1008 failure(s), 3 warning(s) on 107 files.