---

- name: Include KSM tasks
  ansible.builtin.include_tasks: 'ksm_tuning.yml'

- name: Include Packages tasks
  ansible.builtin.include_tasks: 'packages.yml'

- name: Include Subscription Nag tasks
  ansible.builtin.include_tasks: 'subscription_nag.yml'

- name: Include ZFS Tune tasks
  ansible.builtin.include_tasks: 'zfs_tuning.yml'

- name: Include VZDump tasks
  ansible.builtin.include_tasks: 'vzdump.yml'

- name: Configure CPU
  ansible.builtin.include_tasks: 'cpu.yml'  
