---

- name: Include Ansible tasks | gnome
  ansible.builtin.include_tasks: ansible.yml
  
- name: Include App Folders tasks | gnome
  ansible.builtin.include_tasks: app_folders.yml

- name: Include Appearance tasks | gnome
  ansible.builtin.include_tasks: appearance.yml

- name: Include Autostart tasks | gnome
  ansible.builtin.include_tasks: autostart.yml
  when: autostart_tweaks is defined and autostart_tweaks == true

- name: Include Background tasks | gnome
  ansible.builtin.include_tasks: background.yml

- name: Include File Chooser tasks | gnome
  ansible.builtin.include_tasks: file_chooser.yml

- name: Include GPaste tasks | gnome
  ansible.builtin.include_tasks: gpaste.yml
  when: gpaste is defined and gpaste == true

- name: Include Interface tasks | gnome
  ansible.builtin.include_tasks: interface.yml

- name: Include Nautilus tasks | gnome
  ansible.builtin.include_tasks: nautilus.yml

- name: Include Peripherals tasks | gnome
  ansible.builtin.include_tasks: peripherals.yml

- name: Include Power tasks | gnome
  ansible.builtin.include_tasks: power.yml

- name: Include Preferences tasks | gnome
  ansible.builtin.include_tasks: preferences.yml

- name: Include Privacy tasks | gnome
  ansible.builtin.include_tasks: privacy.yml

- name: Include Screensaver tasks | gnome
  ansible.builtin.include_tasks: screensaver.yml

- name: Include Shell tasks | gnome
  ansible.builtin.include_tasks: shell.yml

- name: Include Weather tasks | gnome
  ansible.builtin.include_tasks: weather.yml

- name: Include Dash to Dock tasks | gnome
  ansible.builtin.include_tasks: ubuntu_dash_to_dock.yml
  when: ansible_facts['distribution'] != 'Pop!_OS' # Dont run on PopOS
