---
- name: Set app folder children
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folder-children
    value: "['Pop-Office', 'Pop-System', 'Pop-Utility', '8bee3b57-e158-4b8a-bf52-2744e1238bec', 'a5bd1428-ccb8-44fb-b322-75cf59a87c6a', '021ede3a-8c78-46cc-b292-beeff6dcb577', '809be267-3c4a-4ed0-aeb8-105dd0b1bffe']"

- name: Create Media folder
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/021ede3a-8c78-46cc-b292-beeff6dcb577/apps
    value: "['org.clementine_player.Clementine.desktop', 'google-earth-pro.desktop', 'vlc.desktop', 'org.gnome.gitlab.YaLTeR.VideoTrimmer.desktop', 'de.haeckerfelix.Shortwave.desktop', 'display-im6.q16.desktop']"

- name: Set Media folder name
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/021ede3a-8c78-46cc-b292-beeff6dcb577/name
    value: "'Media'"

- name: Create Engineering folder
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/809be267-3c4a-4ed0-aeb8-105dd0b1bffe/apps
    value: "['org.kicad.KiCad.eeschema.desktop', 'org.kicad.KiCad.pcbnew.desktop', 'org.kicad.KiCad.bitmap2component.desktop', 'org.kicad.KiCad.desktop', 'org.kicad.KiCad.gerbview.desktop', 'org.kicad.KiCad.pcbcalculator.desktop']"

- name: Set Engineering folder name
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/809be267-3c4a-4ed0-aeb8-105dd0b1bffe/name
    value: "'Engineering'"

- name: Create Games folder
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/8bee3b57-e158-4b8a-bf52-2744e1238bec/apps
    value: "['com.endlessnetwork.aqueducts.desktop', 'net.lutris.Lutris.desktop', 'com.obsproject.Studio.desktop', 'com.jagex.RuneScape.desktop', 'discord.desktop']"

- name: Set Games folder name
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/8bee3b57-e158-4b8a-bf52-2744e1238bec/name
    value: "'Games'"

- name: Create Office folder
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/Pop-Office/apps
    value: "['libreoffice-calc.desktop', 'libreoffice-draw.desktop', 'libreoffice-impress.desktop', 'libreoffice-math.desktop', 'libreoffice-startcenter.desktop', 'libreoffice-writer.desktop', 'libreoffice-base.desktop', 'net.codeindustry.MasterPDFEditor.desktop', 'org.zealdocs.Zeal.desktop']"

- name: Set Office folder name
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/Pop-Office/name
    value: "'Office'"

- name: Create System folder
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/Pop-System/apps
    value: "['gnome-language-selector.desktop', 'gnome-session-properties.desktop', 'gnome-system-monitor.desktop', 'im-config.desktop', 'nm-connection-editor.desktop', 'nvidia-settings.desktop', 'org.gnome.baobab.desktop', 'org.gnome.DiskUtility.desktop', 'org.gnome.PowerStats.desktop', 'org.gnome.seahorse.Application.desktop', 'software-properties-gnome.desktop', 'system76-driver.desktop', 'system76-firmware.desktop', 'sublime_text.desktop', 'virtualbox.desktop', 'code.desktop', 'org.gnome.tweaks.desktop', 'org.gnome.Terminal.desktop', 'org.kde.konsole.desktop']"

- name: Set System folder name
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/Pop-System/name
    value: "'System'"

- name: Create Utility folder
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/Pop-Utility/apps
    value: "['com.github.donadigo.eddy.desktop', 'com.system76.Popsicle.desktop', 'gucharmap.desktop', 'info.desktop', 'org.gnome.eog.desktop', 'org.gnome.Evince.desktop', 'org.gnome.Extensions.desktop', 'org.gnome.FileRoller.desktop', 'org.gnome.font-viewer.desktop', 'org.gnome.Screenshot.desktop', 'org.gnome.Totem.desktop', 'pop-cosmic-applications.desktop', 'pop-cosmic-launcher.desktop', 'pop-cosmic-workspaces.desktop', 'simple-scan.desktop', 'yelp.desktop', 'balena-etcher.desktop', 'org.bleachbit.BleachBit.desktop', 'bleachbit-root.desktop', 'io.dbeaver.DBeaverCommunity.desktop', 'ca.desrt.dconf-editor.desktop', 'org.flameshot.Flameshot.desktop', 'org.fedoraproject.MediaWriter.desktop', 'gparted.desktop', 'org.keepassxc.KeePassXC.desktop', 'kazam.desktop', 'htop.desktop', 'sqlitebrowser.desktop', 'com.github.qarmin.czkawka.desktop', 'com.github.weclaw1.ImageRoll.desktop', 'WebHTTrack-Websites.desktop', 'org.remmina.Remmina.desktop', 'stacer.desktop', 'com.belmoussaoui.Obfuscate.desktop', 'org.wireshark.Wireshark.desktop', 'timeshift-gtk.desktop', 'com.github.artemanufrij.regextester.desktop', 'repoman.desktop', 'org.gnome.GPaste.Ui.desktop', 'fr.romainvigier.MetadataCleaner.desktop', 'psensor.desktop', 'WebHTTrack.desktop']"

- name: Set Utility folder name
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/Pop-Utility/name
    value: "'Utilities'"

- name: Create Browser folder
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/a5bd1428-ccb8-44fb-b322-75cf59a87c6a/apps
    value: "['brave-browser.desktop', 'firefox.desktop', 'google-chrome.desktop', 'microsoft-edge-beta.desktop']"

- name: Set Browser folder name
  become_user: "{{ user }}"
  ansible.builtin.dconf:
    key: /org/gnome/desktop/app-folders/folders/a5bd1428-ccb8-44fb-b322-75cf59a87c6a/name
    value: "'Browser'"
