
- name: Gnome | install gpaste
  ansible.builtin.package:
    name: gpaste
    state: present

- name: Gnome | gpaste | History-Name
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/GPaste/history-name"
    value: "'history'"

- name: Gnome | gpaste | Images Support
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/GPaste/images-support"
    value: "true"

- name: Gnome | gpaste | max-displayed-history-size
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/GPaste/max-displayed-history-size"
    value: "uint64 100"

- name: Gnome | gpaste | max-history-size
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/GPaste/max-history-size"
    value: "uint64 300"

- name: Gnome | gpaste | max-memory-usage
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/GPaste/max-memory-usage"
    value: "uint64 100"

- name: Gnome | gpaste | max-text-item-size
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/GPaste/max-text-item-size"
    value: "uint64 3048575"
