---

- name: Gnome | nautilus | set folder view in nautilus
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/default-folder-viewer"
    value: "'list-view'"

- name: Gnome | nautilus | set tree view in nautilus
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/list-view/use-tree-view"
    value: "true"

- name: Gnome | nautilus | enable permanent delete
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/preferences/show-delete-permanently"
    value: "true"

- name: Gnome | nautilus | set directories to not be shown before files in nautilus
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gtk/settings/file-chooser/sort-directories-first"
    value: "true"

- name: Gnome | nautilus | set list view sort column in nautilus
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/list-view/sort-column"
    value: "'search_relevance'"

- name: Gnome | nautilus | set list view sort reversed in nautilus
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/nautilus/list-view/sort-reversed"
    value: "true"

- name: Set Nautilus compression preferences
  become_user: "{{ user }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: '/org/gnome/nautilus/compression/default-compression-format', value: "'tar.xz'" }
