---

- name: Set GNOME window manager preferences
  become_user: "{{ user }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: '/org/gnome/desktop/wm/preferences/button-layout', value: "'appmenu:minimize,maximize,close'" }
    - { key: '/org/gnome/desktop/wm/preferences/num-workspaces', value: 1 }

- name: Set Gedit UI preferences
  become_user: "{{ user }}"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: '/org/gnome/gedit/preferences/ui/show-tabs-mode', value: "'auto'" }
