---

- name: Set GTK4 file chooser settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: '/org/gtk/gtk4/settings/file-chooser/date-format', value: "'regular'" }
    - { key: '/org/gtk/gtk4/settings/file-chooser/location-mode', value: "'path-bar'" }
    - { key: '/org/gtk/gtk4/settings/file-chooser/show-hidden', value: false }
    - { key: '/org/gtk/gtk4/settings/file-chooser/show-size-column', value: true }
    - { key: '/org/gtk/gtk4/settings/file-chooser/show-type-column', value: true }
    - { key: '/org/gtk/gtk4/settings/file-chooser/sidebar-width', value: 162 }
    - { key: '/org/gtk/gtk4/settings/file-chooser/sort-column', value: "'name'" }
    - { key: '/org/gtk/gtk4/settings/file-chooser/sort-directories-first', value: false }
    - { key: '/org/gtk/gtk4/settings/file-chooser/sort-order', value: "'ascending'" }
    - { key: '/org/gtk/gtk4/settings/file-chooser/type-format', value: "'category'" }
    - { key: '/org/gtk/gtk4/settings/file-chooser/window-size', value: "(805, 709)" }
  become_user: "{{ user }}"

- name: Set GTK3 file chooser settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { key: '/org/gtk/settings/file-chooser/date-format', value: "'regular'" }
    - { key: '/org/gtk/settings/file-chooser/location-mode', value: "'path-bar'" }
    - { key: '/org/gtk/settings/file-chooser/show-hidden', value: false }
    - { key: '/org/gtk/settings/file-chooser/show-size-column', value: true }
    - { key: '/org/gtk/settings/file-chooser/show-type-column', value: true }
    - { key: '/org/gtk/settings/file-chooser/sidebar-width', value: 176 }
    - { key: '/org/gtk/settings/file-chooser/sort-column', value: "'name'" }
    - { key: '/org/gtk/settings/file-chooser/sort-directories-first', value: true }
    - { key: '/org/gtk/settings/file-chooser/sort-order', value: "'ascending'" }
    - { key: '/org/gtk/settings/file-chooser/type-format', value: "'category'" }
    - { key: '/org/gtk/settings/file-chooser/window-position', value: "(3942, 845)" }
    - { key: '/org/gtk/settings/file-chooser/window-size', value: "(1096, 820)" }
  become_user: "{{ user }}"
