---

- name: Set color scheme to prefer-dark
  become_user: "{{ user }}"
  community.general.dconf:
    key: /org/gnome/desktop/interface/color-scheme
    value: "'prefer-dark'"

- name: Set font antialiasing to grayscale
  become_user: "{{ user }}"
  community.general.dconf:
    key: /org/gnome/desktop/interface/font-antialiasing
    value: "'grayscale'"

- name: Set font hinting to slight
  become_user: "{{ user }}"
  community.general.dconf:
    key: /org/gnome/desktop/interface/font-hinting
    value: "'slight'"

- name: Set toolkit accessibility to false
  become_user: "{{ user }}"
  community.general.dconf:
    key: /org/gnome/desktop/interface/toolkit-accessibility
    value: false
