---

- name: System setup | tweaks | disable apport in config on ubuntu-based hosts
  ansible.builtin.lineinfile:
    dest: /etc/default/apport
    regexp: "enabled="
    line: "enabled=0"
  failed_when: false
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]

- name: System setup | tweaks | disable and stop apport service on ubuntu-based hosts
  ansible.builtin.service:
    name: apport
    enabled: no
    state: stopped
  failed_when: false
  when: ansible_distribution in ["Pop!_OS", "Ubuntu"]
