---

- name: Gnome | weather | set the weather location
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/shell/weather/locations"
    value: "{{ weather_location }}"

- name: Gnome | weather | Enable Location
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/shell/weather/automatic-location"
    value: "true"
